import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlcipher_flutter_libs/sqlcipher_flutter_libs.dart';

import 'tables/messages_table.dart';
import 'tables/reactions_table.dart';
import 'tables/keys_settings_tables.dart';

part 'app_database.g.dart'; // generated by `dart run build_runner build`

@DriftDatabase(tables: [
  Messages,
  MediaMetadataTable,
  Reactions,
  KeyRecords,
  Settings,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  @override
  int get schemaVersion => 1;

  /// Opens (or creates) the encrypted local database.
  ///
  /// [passphrase] is derived by the crypto module from the device's
  /// secure-enclave key material — it is never hardcoded and never
  /// stored alongside the DB file itself. Losing it means losing the
  /// data; there is no cloud backup by design (see FINAL GOAL: this
  /// world disappears when both users leave).
  static AppDatabase open(String passphrase) {
    final executor = LazyDatabase(() async {
      await applyWorkaroundToOpenSqlCipherOnOldAndroidVersions();
      final dir = await getApplicationSupportDirectory();
      final file = File(p.join(dir.path, 'shared_space.sqlite'));

      return NativeDatabase.createInBackground(
        file,
        setup: (rawDb) {
          final escaped = passphrase.replaceAll("'", "''");
          rawDb.execute("PRAGMA key = '$escaped';");

          final result = rawDb.select('PRAGMA cipher_version;');
          if (result.isEmpty) {
            throw StateError(
              'SQLCipher is not active — refusing to open what would '
              'be an unencrypted database at ${file.path}.',
            );
          }
        },
      );
    });
    return AppDatabase(executor);
  }

  /// In-memory DB for unit tests — no encryption needed for test speed.
  static AppDatabase.forTesting() =>
      AppDatabase(NativeDatabase.memory());
}